import { useEffect, useRef, useState } from 'react';
import { api } from '../api/client';
import type { ApiError, Freshness, IndexJob, OperationEvent, Registration, RepositoryStatus } from '../api/types';
import { formatBytes, formatTime, freshnessLabel } from '../repository-operations';
import { IndexProgress } from '../components/IndexProgress';

function message(error: ApiError) { const copy: Record<string, string> = { protocol_incompatible: 'The daemon protocol is incompatible. Update the configured binary; it was not replaced.', index_in_progress: 'An indexing operation is already running for this repository.', connection_lost: 'The background operation may still be running; live status remains available.' }; return copy[error.code] ?? error.message; }
function phaseLabel(phase: string) { return phase.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function elapsed(started: number, now: number) { return Math.max(0, (now - started) / 1000); }
function provider(status: RepositoryStatus | null) { const value = status?.status?.resources.execution_provider; return value === 'cuda' ? 'CUDA' : value === 'cpu' ? 'CPU' : 'Unavailable'; }

export function RepositoryDetailPage({ id }: { id: string }) {
  const [registration, setRegistration] = useState<Registration | null>(null); const [status, setStatus] = useState<RepositoryStatus | null>(null); const [freshness, setFreshness] = useState<Freshness | null>(null); const [jobs, setJobs] = useState<IndexJob[]>([]); const [events, setEvents] = useState<OperationEvent[]>([]); const [busy, setBusy] = useState(false); const [pendingAction, setPendingAction] = useState<string | null>(null); const [now, setNow] = useState(Date.now()); const [error, setError] = useState<ApiError | null>(null); const [dialog, setDialog] = useState<'remove' | 'rebuild' | null>(null); const loadVersion = useRef(0); const dialogRef = useRef<HTMLButtonElement>(null);
  const load = async () => { const version = ++loadVersion.current; const [r, s, f, j, e] = await Promise.all([api<Registration>(`/repositories/${id}`), api<RepositoryStatus>(`/repositories/${id}/status`), api<Freshness>(`/repositories/${id}/freshness`), api<IndexJob[]>(`/repositories/${id}/jobs`), api<OperationEvent[]>(`/repositories/${id}/events`)]); if (version !== loadVersion.current) return; setRegistration(r); setStatus(s); setFreshness(f); setJobs(j); setEvents(e); };
  useEffect(() => { load().catch((e) => setError(e)); const source = new EventSource('/api/v1/events'); const refresh = () => load().catch(() => undefined); source.addEventListener('status', refresh); source.addEventListener('indexing', refresh); source.addEventListener('operation', refresh); source.addEventListener('reset', refresh); return () => source.close(); }, [id]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []); useEffect(() => { if (!dialog) return; dialogRef.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setDialog(null); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [dialog]);
  const active = jobs.find((job) => job.state === 'queued' || job.state === 'running'); const lastJob = jobs.reduce<IndexJob | null>((latest, job) => !latest || job.updated_at_unix_ms > latest.updated_at_unix_ms ? job : latest, null); const label = freshness ? freshnessLabel(freshness) : { label: 'Loading', tone: 'neutral' as const }; const report = active?.report ?? lastJob?.report ?? status?.status?.last_index?.report; const activeSeconds = active ? elapsed(active.started_at_unix_ms, now) : 0; const throughput = active && active.done > 0 && activeSeconds > 0 ? active.done / activeSeconds : null;
  const run = async (path: string, body?: object, action = 'operation') => { setBusy(true); setPendingAction(action); setError(null); try { const created = await api<IndexJob>(path, { method: 'POST', body: JSON.stringify(body ?? {}) }); setJobs((current) => [created, ...current.filter((job) => job.id !== created.id)]); await load(); } catch (e) { setError(e as ApiError); } finally { setBusy(false); setPendingAction(null); } }; const remove = async () => { setBusy(true); try { await api(`/repositories/${id}`, { method: 'DELETE' }); window.location.assign('/repositories'); } catch (e) { setError(e as ApiError); setBusy(false); } };
  if (!registration && !error) return <div className="panel loading-panel" role="status">Loading repository…</div>; if (error && !registration) return <div className="alert danger" role="alert">{message(error)} <a href="/repositories">Back to repositories</a></div>; const detail = registration!.config;
  return <>
    <header className="page-header compact"><div><a className="back-link" href="/repositories">← Repositories</a><p className="eyebrow">Repository detail</p><h1>{detail.name}</h1><p className="lede path">{detail.repo_path}</p></div><div className="header-actions"><a className="button secondary" href={`/repositories/${id}/edit`}>Edit registration</a><button className="button danger-button" onClick={() => setDialog('remove')} disabled={busy || Boolean(active)}>Remove</button></div></header>
    {error && <div className="alert danger" role="alert"><strong>{error.code}</strong> — {message(error)}</div>}
    {!active && lastJob?.operation_type === 'start_daemon' && lastJob.state === 'failed' && lastJob.error_message && <div className="alert danger" role="alert"><strong>Daemon startup failed</strong> — {lastJob.error_message}</div>}
    {active && <section className="panel live-operation" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">Live operation</p><h2>{active.operation_type === 'start_daemon' ? 'STARTING DAEMON' : active.operation_type === 'full_rebuild' ? 'FULL REBUILD' : 'INDEXING'}</h2></div><span className="status-badge neutral">{phaseLabel(active.phase)}</span></div><IndexProgress phase={phaseLabel(active.phase)} done={active.done} total={active.total} /><div className="operation-facts"><div><span>Elapsed</span><strong>{activeSeconds.toFixed(1)}s</strong></div><div><span>Throughput</span><strong>{throughput ? `${throughput.toFixed(1)} chunks/s` : 'Unavailable'}</strong></div><div><span>Provider</span><strong className={provider(status) === 'CUDA' ? 'provider-cuda' : ''}>{provider(status)}</strong></div><div><span>GPU</span><strong>{status?.status?.resources.device_name ?? status?.status?.resources.device_id ?? 'Unavailable'}</strong></div><div><span>VRAM</span><strong>{formatBytes(status?.status?.resources.device_used_bytes)} / {formatBytes(status?.status?.resources.device_total_bytes)}</strong></div><div><span>Model</span><strong>{status?.status?.model_id ?? 'Unavailable'}</strong></div></div>{active.error_message && <div className="alert danger" role="alert">{active.error_message}</div>}</section>}
    <div className="detail-layout"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Index freshness</p><h2>{label.label}</h2></div><button className="button ghost" onClick={() => load().catch((e) => setError(e))}>Refresh</button></div><div className={`freshness-banner ${label.tone}`}><strong>{label.label}</strong><span>{freshness?.dirty === true ? 'Changes exist in the working tree; the indexed commit alone cannot prove freshness.' : freshness?.dirty === false && freshness.head === freshness.indexed_commit ? 'The indexed commit matches HEAD. Working-tree state is clean at inspection time.' : freshness?.unavailable_reason ?? 'Freshness information is incomplete.'}</span></div><dl className="facts"><div><dt>HEAD</dt><dd>{freshness?.head ?? 'Unborn / unavailable'}</dd></div><div><dt>Indexed commit</dt><dd>{freshness?.indexed_commit ?? 'Unavailable'}</dd></div><div><dt>Inspected</dt><dd>{formatTime(freshness?.inspected_at_unix_ms)}</dd></div><div><dt>Daemon</dt><dd>{status?.connection_state ?? 'Unknown'}</dd></div><div><dt>Live chunks</dt><dd>{status?.status?.chunks_live?.toLocaleString() ?? 'Unavailable'}</dd></div><div><dt>Dead chunks</dt><dd>{status?.status?.chunks_dead?.toLocaleString() ?? 'Unavailable'}</dd></div></dl></section><section className="panel"><p className="eyebrow">Actions</p><h2>Maintain this index</h2><p className="muted">Actions return immediately and continue in the background. Live progress appears above.</p><div className="action-stack"><button className="button primary wide" disabled={busy || Boolean(active)} onClick={() => run(`/repositories/${id}/start`, {}, 'start')}>{pendingAction === 'start' ? 'Starting…' : 'Start daemon'}</button><button className="button secondary wide" disabled={busy || Boolean(active)} onClick={() => run(`/repositories/${id}/index`, { mode: 'update' }, 'update')}>{pendingAction === 'update' ? 'Queuing…' : 'Update index'}</button><button className="button outline-danger wide" disabled={busy || Boolean(active)} onClick={() => setDialog('rebuild')}>Full rebuild</button></div></section></div>
    <section className="panel report-panel"><div className="section-heading"><div><p className="eyebrow">Latest report</p><h2>{report ? `Indexed ${report.commit}` : 'No completed indexing report'}</h2></div>{lastJob && <span className={`status-badge ${lastJob.state === 'succeeded' ? 'success' : lastJob.state === 'failed' ? 'danger' : 'neutral'}`}>{lastJob.state}</span>}</div>{report ? <div className="report-grid">{[['Files seen', report.files_seen], ['Files indexed', report.files_indexed], ['Excluded', report.files_excluded], ['Unsupported', report.files_unsupported], ['Unparsed', report.files_unparsed], ['Chunks added', report.chunks_added], ['Chunks reused', report.chunks_reused], ['Chunks removed', report.chunks_removed], ['Live after', report.live_after], ['Wall time', `${report.wall_millis} ms`]].map(([name, value]) => <div className="report-stat" key={String(name)}><span>{name}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></div>)}</div> : <p className="muted">Reports appear after an indexing operation completes.</p>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Resource snapshot</p><h2>Observed daemon state</h2></div><span className={`status-badge ${provider(status) === 'CUDA' ? 'success' : 'neutral'}`}>{provider(status)}</span></div><dl className="facts"><div><dt>Model</dt><dd>{status?.status?.model_id ?? 'Unavailable'}</dd></div><div><dt>Device</dt><dd>{status?.status?.resources.device_name ?? status?.status?.resources.device_id ?? 'Unavailable'}</dd></div><div><dt>Device memory</dt><dd>{formatBytes(status?.status?.resources.device_used_bytes)} / {formatBytes(status?.status?.resources.device_total_bytes)}</dd></div><div><dt>Device utilization</dt><dd>{status?.status?.resources.device_utilization_percent == null ? 'Unavailable' : `${status.status.resources.device_utilization_percent}%`}</dd></div><div><dt>Process memory</dt><dd>{formatBytes(status?.status?.resources.process_used_bytes)}</dd></div><div><dt>Daemon uptime</dt><dd>{status?.status?.uptime_seconds == null ? 'Unavailable' : `${status.status.uptime_seconds}s`}</dd></div></dl></section>
    <section className="panel event-log"><div className="section-heading"><div><p className="eyebrow">Live event log</p><h2>Recent operation events</h2></div><span className="muted">{events.length} events</span></div>{events.length ? <ol>{events.slice(-30).reverse().map((event, index) => <li key={`${event.at_unix_ms}-${index}`}><time>{new Date(event.at_unix_ms).toLocaleTimeString()}</time><strong>{phaseLabel(event.phase)}</strong><span>{event.message}</span></li>)}</ol> : <p className="muted">No operation events recorded yet.</p>}</section>
    {dialog && <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><p className="eyebrow">Confirm action</p><h2 id="confirm-title">{dialog === 'remove' ? 'Remove this registration?' : 'Run a full rebuild?'}</h2><p>{dialog === 'remove' ? 'This removes the console registration and its metadata. Project files and index files remain untouched.' : 'A full rebuild reprocesses the repository and can use significant CPU, GPU, and disk time.'}</p><div className="form-actions"><button ref={dialogRef} className="button secondary" onClick={() => setDialog(null)}>Cancel</button>{dialog === 'remove' ? <button className="button danger-button" disabled={busy} onClick={() => { setDialog(null); void remove(); }}>Remove registration</button> : <button className="button danger-button" disabled={busy} onClick={() => { setDialog(null); void run(`/repositories/${id}/index`, { mode: 'full' }, 'rebuild'); }}>Start full rebuild</button>}</div></div></div>}
  </>;
}
