import { useEffect, useRef, useState } from 'react';
import { api } from '../api/client';
import type { ApiError, Freshness, IndexJob, Registration, RepositoryStatus } from '../api/types';
import { formatBytes, formatTime, freshnessLabel } from '../repository-operations';
import { IndexProgress } from '../components/IndexProgress';

function message(error: ApiError) {
  const copy: Record<string, string> = { starting: 'The daemon is starting. Refresh status in a moment.', protocol_incompatible: 'The daemon protocol is incompatible. Update the configured binary; it was not replaced.', store_stale: 'The index is stale. Run an explicit update or full rebuild.', daemon_unavailable: 'The daemon could not be reached. Check the configured paths.', index_in_progress: 'An indexing operation is already running for this repository.', connection_lost: 'The response was lost. The operation may still be running; refresh before retrying.' };
  return copy[error.code] ?? error.message;
}

export function RepositoryDetailPage({ id }: { id: string }) {
  const [registration, setRegistration] = useState<Registration | null>(null);
  const [status, setStatus] = useState<RepositoryStatus | null>(null);
  const [freshness, setFreshness] = useState<Freshness | null>(null);
  const [jobs, setJobs] = useState<IndexJob[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);
  const [dialog, setDialog] = useState<'remove' | 'rebuild' | null>(null);
  const loadVersion = useRef(0); const dialogRef = useRef<HTMLButtonElement>(null);
  const load = async () => { const version = ++loadVersion.current; const [r, s, f, j] = await Promise.all([api<Registration>(`/repositories/${id}`), api<RepositoryStatus>(`/repositories/${id}/status`), api<Freshness>(`/repositories/${id}/freshness`), api<IndexJob[]>(`/repositories/${id}/jobs`)]); if (version !== loadVersion.current) return; setRegistration(r); setStatus(s); setFreshness(f); setJobs(j); };
  useEffect(() => { load().catch((e) => setError(e)); const source = new EventSource('/api/v1/events'); const refresh = () => load().catch(() => undefined); source.addEventListener('status', refresh); source.addEventListener('indexing', refresh); source.addEventListener('reset', refresh); return () => source.close(); }, [id]);
  useEffect(() => { if (!dialog) return; dialogRef.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setDialog(null); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [dialog]);
  const running = jobs.find((job) => job.state === 'running'); const lastJob = jobs[jobs.length - 1]; const label = freshness ? freshnessLabel(freshness) : { label: 'Loading', tone: 'neutral' as const }; const report = running?.report ?? lastJob?.report ?? status?.status?.last_index?.report;
  const run = async (path: string, body?: object) => { setBusy(true); setError(null); try { await api(path, { method: 'POST', body: JSON.stringify(body ?? {}) }); await load(); } catch (e) { setError(e as ApiError); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await api(`/repositories/${id}`, { method: 'DELETE' }); window.location.assign('/repositories'); } catch (e) { setError(e as ApiError); setBusy(false); } };
  if (!registration && !error) return <div className="panel loading-panel" role="status">Loading repository…</div>;
  if (error && !registration) return <div className="alert danger" role="alert">{message(error)} <a href="/repositories">Back to repositories</a></div>;
  const detail = registration!.config;
  return <>
    <header className="page-header compact"><div><a className="back-link" href="/repositories">← Repositories</a><p className="eyebrow">Repository detail</p><h1>{detail.name}</h1><p className="lede path">{detail.repo_path}</p></div><div className="header-actions"><a className="button secondary" href={`/repositories/${id}/edit`}>Edit registration</a><button className="button danger-button" onClick={() => setDialog('remove')} disabled={busy || Boolean(running)}>Remove</button></div></header>
    {error && <div className="alert danger" role="alert">{message(error)}</div>}
    <div className="detail-layout"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Index freshness</p><h2>{label.label}</h2></div><button className="button ghost" onClick={() => load().catch((e) => setError(e))}>Refresh</button></div><div className={`freshness-banner ${label.tone}`}><strong>{label.label}</strong><span>{freshness?.dirty === true ? 'Changes exist in the working tree; the indexed commit alone cannot prove freshness.' : freshness?.dirty === false && freshness.head === freshness.indexed_commit ? 'The indexed commit matches HEAD. Working-tree state is clean at inspection time.' : freshness?.unavailable_reason ?? 'Freshness information is incomplete.'}</span></div><dl className="facts"><div><dt>HEAD</dt><dd>{freshness?.head ?? 'Unborn / unavailable'}</dd></div><div><dt>Indexed commit</dt><dd>{freshness?.indexed_commit ?? 'Unavailable'}</dd></div><div><dt>Inspected</dt><dd>{formatTime(freshness?.inspected_at_unix_ms)}</dd></div><div><dt>Daemon</dt><dd>{status?.connection_state ?? 'Unknown'}</dd></div><div><dt>Live chunks</dt><dd>{status?.status?.chunks_live?.toLocaleString() ?? 'Unavailable'}</dd></div><div><dt>Dead chunks</dt><dd>{status?.status?.chunks_dead?.toLocaleString() ?? 'Unavailable'}</dd></div></dl></section>
      <section className="panel"><p className="eyebrow">Actions</p><h2>Maintain this index</h2><p className="muted">Incremental update is the default. Full rebuild reprocesses the repository and may take substantially longer.</p><div className="action-stack"><button className="button primary wide" disabled={busy || Boolean(running)} onClick={() => run(`/repositories/${id}/start`)}>Start daemon</button><button className="button secondary wide" disabled={busy || Boolean(running)} onClick={() => run(`/repositories/${id}/index`, { mode: 'update' })}>Update index</button><button className="button outline-danger wide" disabled={busy || Boolean(running)} onClick={() => setDialog('rebuild')}>Full rebuild</button></div>{running && <div className="inline-status"><IndexProgress phase={String(running.progress ?? 'Starting')} done={running.done} total={running.total} /></div>}</section></div>
    <section className="panel report-panel"><div className="section-heading"><div><p className="eyebrow">Latest report</p><h2>{report ? `Indexed ${report.commit}` : 'No completed indexing report'}</h2></div>{lastJob && <span className={`status-badge ${lastJob.state === 'succeeded' ? 'success' : lastJob.state === 'failed' ? 'danger' : 'neutral'}`}>{lastJob.state}</span>}</div>{report ? <div className="report-grid">{[['Files seen', report.files_seen], ['Files indexed', report.files_indexed], ['Excluded', report.files_excluded], ['Unsupported', report.files_unsupported], ['Unparsed', report.files_unparsed], ['Chunks added', report.chunks_added], ['Chunks reused', report.chunks_reused], ['Chunks removed', report.chunks_removed], ['Live after', report.live_after], ['Wall time', `${report.wall_millis} ms`]].map(([name, value]) => <div className="report-stat" key={String(name)}><span>{name}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></div>)}</div> : <p className="muted">Reports appear after an indexing operation completes. Exclusion counts describe paths skipped by policy; their contents are never displayed here.</p>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Resource snapshot</p><h2>Observed daemon state</h2></div><span className="status-badge neutral">{status?.status?.lifecycle ?? 'unavailable'}</span></div><dl className="facts"><div><dt>Model</dt><dd>{status?.status?.model_id ?? 'Unavailable'}</dd></div><div><dt>Device memory</dt><dd>{formatBytes(status?.status?.resources.device_used_bytes)} / {formatBytes(status?.status?.resources.device_total_bytes)}</dd></div><div><dt>Process memory</dt><dd>{formatBytes(status?.status?.resources.process_used_bytes)}</dd></div><div><dt>Observed</dt><dd>{formatTime(status?.status?.observed_at_unix_ms)}</dd></div></dl></section>
    {dialog && <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><p className="eyebrow">Confirm action</p><h2 id="confirm-title">{dialog === 'remove' ? 'Remove this registration?' : 'Run a full rebuild?'}</h2><p>{dialog === 'remove' ? 'This removes the console registration and its metadata. Project files and index files remain untouched.' : 'A full rebuild reprocesses the repository and can use significant CPU, GPU, and disk time.'}</p><div className="form-actions"><button ref={dialogRef} className="button secondary" onClick={() => setDialog(null)}>Cancel</button>{dialog === 'remove' ? <button className="button danger-button" disabled={busy} onClick={() => { setDialog(null); void remove(); }}>Remove registration</button> : <button className="button danger-button" disabled={busy} onClick={() => { setDialog(null); void run(`/repositories/${id}/index`, { mode: 'full' }); }}>Start full rebuild</button>}</div></div></div>}
  </>;
}
