import { useEffect, useRef, useState } from 'react';
import type { RegistrationInput } from '../api/types';
import { emptyRepositoryForm, firstInvalidField, mapRepositoryError } from '../repository-operations';

export function RepositoryForm({ initialValues = emptyRepositoryForm, onSave, onCancel, saving = false, serverError }: { initialValues?: RegistrationInput; onSave: (values: RegistrationInput) => Promise<void>; onCancel: () => void; saving?: boolean; serverError?: { code: string; message: string } | null }) {
  const [values, setValues] = useState(initialValues); const [error, setError] = useState<{ field: keyof RegistrationInput | null; message: string } | null>(null); const firstError = useRef<HTMLInputElement>(null);
  useEffect(() => { setValues(initialValues); }, [initialValues]); useEffect(() => { if (error?.field) firstError.current?.focus(); }, [error]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const field = firstInvalidField(values); if (field) { setError({ field, message: 'Enter a value for this field.' }); return; } try { setError(null); await onSave(values); } catch (raw) { const apiError = raw as { code?: string; message?: string }; setError(mapRepositoryError({ code: apiError.code ?? 'invalid_registration', message: apiError.message ?? 'Check the highlighted values.', retryable: false }, values)); } };
  const update = (field: keyof RegistrationInput, value: string) => setValues((current) => ({ ...current, [field]: value }));
  const fields: Array<[keyof RegistrationInput, string, string]> = [['name', 'Display name', 'A short name for this repository'], ['repo_path', 'Repository path', '/absolute/path/to/repository'], ['store_path', 'Index store path', '/absolute/path/to/store'], ['model_path', 'Model path', '/absolute/path/to/model'], ['daemon_path', 'Daemon executable', '/absolute/path/to/sift-daemon']];
  return <form className="panel form-panel" onSubmit={submit} noValidate><div className="section-heading"><div><p className="eyebrow">Registration</p><h2>{initialValues === emptyRepositoryForm ? 'Attach a repository' : 'Edit registration'}</h2></div><p className="muted">Paths are saved exactly as configured after server validation.</p></div>{serverError && <div className="alert danger" role="alert">{serverError.message}</div>}<div className="form-grid">{fields.map(([field, label, hint], index) => <label className="field" key={field}>{label}<input ref={index === 0 || error?.field === field ? firstError : undefined} value={values[field]} onChange={(event) => update(field, event.target.value)} aria-invalid={error?.field === field} aria-describedby={`${field}-hint ${error?.field === field ? `${field}-error` : ''}`} /><span className="field-hint" id={`${field}-hint`}>{hint}</span>{error?.field === field && <span className="field-error" id={`${field}-error`} role="alert">{error.message}</span>}</label>)}</div><div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save registration'}</button></div></form>;
}
